SELECT blocks.LOC_ID, blocks.START_IP_NUM, blocks.END_IP_NUM, 
       locs.COUNTRY, locs.CITY, locs.LATITUDE, locs.LONGITUDE  
FROM I827779.CITY_IP_BLOCKS blocks,
     I827779.CITY_LOCATIONS locs
WHERE blocks.LOC_ID = locs.LOC_ID
AND blocks.LOC_ID in (
	SELECT LOC_ID
	FROM ( SELECT LOC_ID, COUNT(0) 
		   FROM I827779.CITY_IP_BLOCKS
		   GROUP BY LOC_ID
		   ORDER BY 2 DESC
		   LIMIT 100000 ))